### ISSUE TITLE
Speaking text containing an apostrophe with NVDA causes a mispronounciation.

### ISSUE THREAD

**Issue by blindgoofball** [m1maker/SRAL#10]
If you try to speak a string with NVDA containing an apostrophe, for example "Bob's", NVDA will pronounce the text wrong. IT will say "Bob s" instead of the expected "bobs". This can easily be tested in the sral test program. Enter something with aan apostrophe when NVDA is the active engine. The same issue does not seem to occur with SAPI, so it is likely an issue with the way you are using NVDA.

**Comment by m1maker** [comment]
Hello.
Unfortunately, this is a strange NVDA apparition with SpeakSsml.
The thing is, regular Speak inside will still use SpeakSsml to maintain the symbol level and other parameters.
I don't know, most likely you need to open an issue in NVDA.

**Comment by blindgoofball** [comment]
If I remember correctly from looking at the code yesterday, the normal speak function uses speak ssml anyway. You might consider adding a third argument that causes it to use a standard speak function instead of ssml. I am fairly certain NVDA allows you to do this, and it would fix the problem I think.

**Comment by m1maker** [comment]
But symbol level and other features will not work.

**Comment by blindgoofball** [comment]
Hello.

I’ve just submitted a pull request that fixes this issue. I tested it out, and using the normal speak text function does not affect symbol level after all. I also left the old code in the NVDA speak function commented out in case it is needed later.

**Comment by m1maker** [comment]
I opened the issue in the NVDA repository.
Click [here](https://github.com/nvaccess/nvda/issues/17389) to view it.
