### ISSUE TITLE
The library does not detect Jws before SAPI when using the python bindings.

### ISSUE THREAD

**Issue by blindgoofball** [m1maker/SRAL#9]
It appears that SAPI, or some other engine that speaks with SAPI, takes presidence over JAWS in the auto detection on windows. When I initialized the libary with the python bindings, it will use NVDA, but it won't use JAWS.

**Comment by m1maker** [comment]
Provide an example code you using.

**Comment by blindgoofball** [comment]
Certainly. Here’s the code I use. I was also looking at the code and may have found what is wrong, more on that after the code.

 

import sral

s=sral.Sral()

s.speak('Hello.')

 

This code will speak with NVDA, but not Jaws. It uses SAPI instead when jaws is running.

As for what I found in the code, I think it has something to do with the initialize function. When you’re adding the engines to the vector, you add SAPI before jaws, which I think is the problem. I could be wrong, and unfortunately I don’t own JAWS myself to test this. I discovered this issue when having a friend who runs jaws run this code.

I hope this helps.

**Comment by m1maker** [comment]
Okay. Try to use latest commit.

**Comment by blindgoofball** [comment]
I’ve got  question. Since I use the python bindings, is there a certain way I have to build the library? I tried on an older version to write my own bindings before there were any, and ctypes couldn’t load the dll.

**Comment by m1maker** [comment]
You can download Windows DLL from [here](https://github.com/m1maker/SRAL/actions/runs/11526041364/artifacts/2106369879)

**Comment by m1maker** [comment]
The library in the Release folder. Also, you can check how CTypes loading DLL at Sral::__init__().

**Comment by blindgoofball** [comment]
This appears to have fixed the issue. However, it seems like the dll I get from building is different from the one you are getting, as python can’t load it, even if I make sure it has the same name. To build it, I run cmake with the argument to specify mingw makefiles. Then I just run make. Are there other arguments you pass to it?

**Comment by m1maker** [comment]
Perhaps you are running SRAL on a 32 bit system? What specific error does it give?

**Comment by blindgoofball** [comment]
I am running on a 64bit system with 64bit python and a 64bit compiler. When I load it into python it just says something like: “could not find sral or one of its dependancies”.

**Comment by m1maker** [comment]
This strange. DLL should be placed with sral.py file.
I building via these commands:
```
cmake -B build
cmake --build build --config Release
```

**Comment by blindgoofball** [comment]
Thank you. It appears to be building correctly now, and JAWS works as expected.
